version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    external_links:
      - node-exporter:nodeexporter
      - grafana:grafana
      - gpuexporter:gpuexporter
    networks:
      - mynet
    depends_on:
      - node-exporter
      - grafana
      - gpuexporter

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9101:9100
    networks:
      - mynet

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    user: '472'
    ports:
      - 3000:3000
    networks:
      - mynet

  gpuexporter:
    image: linnil1/nvidia-smi
    devices:
      - /dev/nvidia0
      - /dev/nvidia1
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    volumes:
      - nvidia_driver_375.66:/usr/local/nvidia/:ro
    ports:
      - 9102:9102
    networks:
      - mynet

networks:
  mynet:
    external:
      name: dockercompose_mynet

volumes:
  nvidia_driver_375.66:
    external: true
