{
 "title": "Toolmen DashBoard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server_job", "query": "up{job='node-exporter'}" },
   {
    "name": "gpu_job",
    "query": "nvidia_utilization_gpu{job='gpuexporter'}"
   },
   {
    "name": "gpus",
    "query": "nvidia_utilization_gpu{job='$gpu_job'}"
   },
   {
    "name": "ups_job",
    "query": "apcupsd_battery_time_left_seconds{job='apcupsd'}"
   },
   { "name": "nas_job", "query": "hrStorageUsed" }
  ]
 },
 "panels": [
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{job='$server_job'}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{job='$server_job',mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total{job='$server_job'}) by (cpu))"
      }
     ]
    },
    {
     "title": "Ram Uasgae",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{job='$server_job'} * 100) / node_memory_MemTotal_bytes{job='$server_job'})"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(time() - node_boot_time_seconds{job='$server_job'}) / 86400"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job='$server_job',mode!='idle'}[5m]))",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job='$server_job'}- node_memory_MemFree_bytes{job='node-exporter'} - node_memory_Buffers_bytes{job='node-exporter'} - node_memory_Cached_bytes{job='node-exporter'}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Buffers_bytes{job='$server_job'}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{job='$server_job'}",
       "legendFormat": "Cached"
      }
     ]
    },
    {
     "title": "System load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "expr": "node_load1{job='$server_job'}", "legendFormat": "node_load1" },
      { "expr": "node_load5{job='$server_job'}", "legendFormat": "node_load5" },
      { "expr": "node_load15{job='$server_job'}", "legendFormat": "node_load15" }
     ]
    },
    {
     "title": "Temparature",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{job='$server_job'}",
       "legendFormat": "{{chip}} {{sensor}}"
      }
     ]
    },
    {
     "title": "Disk I/O Utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{job='$server_job',device!~'^(md\\\\d+$|dm-)'}[5m]) / 1000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Filesystem Fullness",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{job='$server_job',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job='$server_job'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job='$server_job',device='bond0'}[5m])",
       "legendFormat": "{{device}} receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job='$server_job',device='bond0'}[5m])",
       "legendFormat": "{{device}} transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU usage",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(nvidia_utilization_gpu{job='$gpu_job'}) / count(nvidia_utilization_gpu{job='$gpu_job'})"
      }
     ]
    },
    {
     "title": "GPU memory",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(nvidia_memory_used{job='$gpu_job'}) / sum(nvidia_memory_total{job='$gpu_job'}) * 100"
      }
     ]
    },
    {
     "title": "GPU utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "nvidia_utilization_gpu{job='$gpu_job'}",
       "legendFormat": "{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nvidia_memory_used{job='$gpu_job'} * 1000000",
       "legendFormat": "Used {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Temparature",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "nvidia_temperature_gpu{job='$gpu_job'}",
       "legendFormat": "{{gpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "APC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery Time Left",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "apcupsd_battery_time_left_seconds{job='$ups_job'}",
       "legendFormat": "{{model}}"
      }
     ]
    },
    {
     "title": "AC Voltage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "expr": "apcupsd_line_nominal_volts{job='$ups_job'}",
       "legendFormat": "nominal"
      },
      {
       "expr": "apcupsd_line_volts{job='$ups_job'}",
       "legendFormat": "actual"
      }
     ]
    },
    {
     "title": "Battery Charge Percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "apcupsd_battery_charge_percent{job='$ups_job'}",
       "legendFormat": "{{model}}"
      }
     ]
    },
    {
     "title": "UPS Load Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "apcupsd_ups_load_percent{job='$ups_job'}",
       "legendFormat": "{{model}}"
      }
     ]
    },
    {
     "title": "APC Watts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "apcupsd_apcupsd_nominal_power_watts{job='$ups_job'} * (apcupsd_ups_load_percent{job='$ups_job'} / 100)",
       "legendFormat": "{{model}}"
      },
      {
       "expr": "apcupsd_apcupsd_nominal_power_watts{job='$ups_job'}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Battery Voltage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "expr": "apcupsd_battery_nominal_volts{job='$ups_job'}",
       "legendFormat": "nominal"
      },
      {
       "expr": "apcupsd_battery_volts{job='$ups_job'}",
       "legendFormat": "actual"
      }
     ]
    },
    {
     "title": "Current Time On Battery",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 51 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "apcupsd_battery_time_on_seconds{job='$ups_job'}"
      }
     ]
    },
    {
     "title": "Cumulative Time On Battery",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 51 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "apcupsd_battery_cumulative_time_on_seconds_total{job='$ups_job'}"
      }
     ]
    },
    {
     "title": "Last Discharged Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 51 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(time() - apcupsd_apcupsd_last_transfer_off_battery{job='$ups_job'}) / 86400"
      }
     ]
    }
   ]
  },
  {
   "title": "Nas $nas_job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "nas_job",
   "collapsed": true,
   "panels": [
    {
     "title": "systemFanStatus",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "systemFanStatus{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "cpuFanStatus",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "cpuFanStatus{job='$nas_job'}" }
     ]
    },
    {
     "title": "powerStatus",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "powerStatus{job='$nas_job'}" }
     ]
    },
    {
     "title": "systemStatus",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "systemStatus{job='$nas_job'}" }
     ]
    },
    {
     "title": "Disk Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "targets": [
      { "expr": "diskStatus{job='$nas_job'}" }
     ]
    },
    {
     "title": "Trafick",
     "type": "graph",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{job='$nas_job'}[5m])",
       "legendFormat": "In {{ifName}}"
      },
      {
       "expr": "irate(ifHCOutOctets{job='$nas_job'}[5m])",
       "legendFormat": "Out {{ifName}}"
      }
     ]
    },
    {
     "title": "Temperture",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "diskTemperature{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "ssCpuUser{job='$nas_job'} + ssCpuSystem{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "1 - (memCached{job='$nas_job'} + memAvailReal{job='$nas_job'}) / memTotalReal{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "1 - memAvailSwap{job='$nas_job'} / memTotalSwap{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(storageIOLA{job='$nas_job'})"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 18 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hrStorageUsed{job='$nas_job'}) / sum(hrStorageSize{job='$nas_job'})"
      }
     ]
    },
    {
     "title": "temperature",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
     "format": "celsius",
     "valueName": "current",
     "targets": [
      { "expr": "temperature{job='$nas_job'}" }
     ]
    },
    {
     "title": "Disk Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "storageIOLA{job='$nas_job'}", "legendFormat": "{{storageIODevice}}" }
     ]
    },
    {
     "title": "Volume Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "spaceIOLA15{job='$nas_job'}", "legendFormat": "load15" },
      { "expr": "spaceIOLA5{job='$nas_job'}", "legendFormat": "load5" },
      { "expr": "spaceIOLA1{job='$nas_job'}", "legendFormat": "load1" }
     ]
    },
    {
     "title": "Read  Write Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(spaceIONReadX{job='$nas_job'}[5m])",
       "legendFormat": "Read {{storageIODevice}}"
      },
      {
       "expr": "irate(spaceIONWrittenX{job='$nas_job'}[5m])",
       "legendFormat": "Write {{storageIODevice}}"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "laLoadInt{job='$nas_job'}", "legendFormat": "{{laNames}}" }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      { "expr": "memTotalReal{job='$nas_job'}", "legendFormat": "Total" },
      { "expr": "memAvailReal{job='$nas_job'}", "legendFormat": "Available" },
      { "expr": "memCached{job='$nas_job'}", "legendFormat": "Cache" },
      { "expr": "memBuffer{job='$nas_job'}", "legendFormat": "Buffer" },
      { "expr": "memShared{job='$nas_job'}", "legendFormat": "Share" }
     ]
    },
    {
     "title": "RAID Status",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 39 },
     "targets": [
      { "expr": "raidStatus{job='$nas_job'}" }
     ]
    }
   ]
  }
 ]
}