{
 "title": "LabServer_monitor",
 "description": "LabServer_monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Machine",
    "query": "up{job=\"node-exporter\"}"
   },
   { "name": "job", "label": "job", "query": "node-exporter" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\",mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Ram Uasgae",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"$job\",instance=\"$instance\"} - node_memory_MemFree_bytes{job=\"$job\",instance=\"$instance\"}) / (node_memory_MemTotal_bytes{job=\"$job\",instance=\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "GPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nvidia_utilization_gpu) / count(nvidia_utilization_gpu)"
    }
   ]
  },
  {
   "title": "GPU memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nvidia_memory_used) / sum(nvidia_memory_total)"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "node_load1" },
    { "expr": "node_load5", "legendFormat": "node_load5" },
    { "expr": "node_load15", "legendFormat": "node_load15" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='$job',instance='$instance'} - node_memory_MemFree_bytes{job='node-exporter',instance='$instance'} - node_memory_Buffers_bytes{job='node-exporter',instance='$instance'} - node_memory_Cached_bytes{job='node-exporter',instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nvidia_utilization_gpu", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nvidia_memory_used * 1000000", "legendFormat": "Used {{gpu}}" }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='$job',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job='$job',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job='$job',instance='$instance'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Temparature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "GPU Temparature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "nvidia_temperature_gpu", "legendFormat": "{{gpu}}" }
   ]
  }
 ]
}