global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
         - targets: ['nodeexporter:9100']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
         - targets: ['grafana:3000']

  - job_name: 'gpuexporter'
    scrape_interval: 5s
    static_configs:
         - targets: ['gpuexporter:9101']

  - job_name: 'apcupsd'
    scrape_interval: 5s
    static_configs:
         - targets: ['192.168.0.1:9162']
