{
 "title": "Prometheus Synology SNMP  DashBoard",
 "description": "Work with prometheus, snmp-exporter with synology module",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" },
   {
    "name": "Device",
    "query": "query_result(sum by (instance)(ifInOctets{job=\"$job\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "systemFanStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemFanStatus{job='$job', instance='$Device'}"
    }
   ]
  },
  {
   "title": "cpuFanStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cpuFanStatus{job='$job', instance='$Device'}"
    }
   ]
  },
  {
   "title": "powerStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerStatus{job='$job', instance='$Device'}"
    }
   ]
  },
  {
   "title": "systemStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemStatus{job='$job', instance='$Device'}"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "diskStatus{job=\"$job\", instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Temperture",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "diskTemperature{job=\"$job\", instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Trafick",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='$job',instance='$Device'}[5m])",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{job='$job',instance='$Device'}[5m])",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "RAID Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "raidStatus{job=\"$job\", instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "ssCpuUser{job='$job',instance='$Device'} + ssCpuSystem{job='$job',instance='$Device'}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (memCached{job='$job',instance='$Device'} + memAvailReal{job='$job',instance='$Device'}) / memTotalReal{job='$job',instance='$Device'}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - memAvailSwap{job='$job',instance='$Device'} / memTotalSwap{job='$job',instance='$Device'}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(storageIOLA{job='$job',instance='$Device'})"
    }
   ]
  },
  {
   "title": "Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hrStorageUsed{job='$job',instance='$Device'}) / sum(hrStorageSize{job='$job',instance='$Device'})"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "temperature{job=\"$job\", instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "storageIOLA{job='$job', instance='$Device'}",
     "legendFormat": "{{storageIODevice}}"
    }
   ]
  },
  {
   "title": "Volume Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "spaceIOLA15{job='$job', instance='$Device'}",
     "legendFormat": "load15"
    },
    {
     "expr": "spaceIOLA5{job='$job', instance='$Device'}",
     "legendFormat": "load5"
    },
    {
     "expr": "spaceIOLA1{job='$job', instance='$Device'}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "title": "Read  Write Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(spaceIONReadX{job='$job', instance='$Device'}[5m])",
     "legendFormat": "Read {{storageIODevice}}"
    },
    {
     "expr": "irate(spaceIONWrittenX{job='$job', instance='$Device'}[5m])",
     "legendFormat": "Write {{storageIODevice}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "laLoadInt{job='$job',instance='$Device'}",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{job='$job',instance='$Device'}",
     "legendFormat": "Total"
    },
    {
     "expr": "memAvailReal{job='$job',instance='$Device'}",
     "legendFormat": "Available"
    },
    {
     "expr": "memCached{job='$job',instance='$Device'}",
     "legendFormat": "Cache"
    },
    {
     "expr": "memBuffer{job='$job',instance='$Device'}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memShared{job='$job',instance='$Device'}",
     "legendFormat": "Share"
    }
   ]
  }
 ]
}