apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apcupsd-exporter
  namespace: monitor
spec:
  selector:
    matchLabels:
      name: apcupsd-exporter
  template:
    metadata:
      labels:
        name: apcupsd-exporter
    spec:
      containers:
      - name: apcupsd-exporter
        image: registry.default.svc.cluster.local/linnil1/apcupsd_exporter
        command: [./main]
        args: ['-apcupsd.addr', '$(NODE_IP):3551']
        ports:
        - containerPort: 9162
          protocol: TCP
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
