---
apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: monitor
spec:
  selector:
    name: blackbox
  ports:
  - port: 9115
    targetPort: 9115
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-dep
  namespace: monitor
spec:
  selector:
    matchLabels:
      name: blackbox
  replicas: 1
  template:
    metadata:
      labels:
        name: blackbox
    spec:
      containers:
      - name: blackbox
        image: prom/blackbox-exporter
        ports:
        - containerPort: 9115
          protocol: TCP
        volumeMounts:
        - name: blackbox-config
          mountPath: /etc/blackbox_exporter/config.yml
          subPath: blackbox.yml
      volumes:
      - name: blackbox-config
        persistentVolumeClaim:
          claimName: nfs-monitor
