ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  hosts:
   - ' '
  path: /monitor/
image:
  tag: 7.0.5
testFramework:
  enabled: false
persistence:
  enabled: true
  existingClaim: nfs-monitor
  subPath: grafana_data
env:
  GF_PATHS_PROVISIONING: /var/lib/grafana/provis
  GF_PATHS_PLUGINS: /var/lib/grafana/plugins
  GF_PATHS_LOGS: /var/lib/grafana/log
  GF_PATHS_DATA: /var/lib/grafana
plugins:
  - grafana-piechart-panel

grafana.ini:
  default:
    instance_name: {{ name }} - Grafana
  log:
    mode: console file
  users:
    allow_sign_up: false
  analytics:
    check_for_updates: true
  server:
    root_url: {{ domain_url }}/monitor/
  auth:
    disable_login_form: true
  auth.generic_oauth:
    name: {{ grafana.oauth_name }}
    enabled: true
    client_id: {{ grafana.oauth_id }}
    client_secret: {{ grafana.oauth_secret }}
    api_url :  {{ domain_url }}/oauth/profile
    auth_url:  {{ domain_url }}/oauth/authorize
    token_url: {{ domain_url }}/oauth/token
    allowed_domains: {{ domain }}
    scopes: profile
    allow_sign_up: true
  security:
    cookie_secure: true
    cookie_samesite: disabled
