apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-exporter
  namespace: monitor
spec:
  selector:
    matchLabels:
      name: nvidia-exporter
  template:
    metadata:
      labels:
        name: nvidia-exporter
    spec:
      containers:
      - name: nvidia-exporter
        image: mindprince/nvidia_gpu_prometheus_exporter:0.1
        ports:
        - containerPort: 9101
          protocol: TCP
