apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-monitor
spec:
  storageClassName: nfs-monitor
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    server: $IP_NAS
    path: $NAS_MONITOR_PATH/grafana_data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-monitor
  namespace: monitor
spec:
  storageClassName: nfs-monitor
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
