apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-monitor
spec:
  storageClassName: nfs-monitor
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Ti
  nfs:
    server: {{ nfs.ip }}
    path: {{ nfs.path }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-monitor
  namespace: monitor
spec:
  storageClassName: nfs-monitor
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
