apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-monitor-prometheus
spec:
  storageClassName: nfs-monitor-prometheus
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: $IP_NAS
    path: $NAS_MONITOR_PATH/prometheus_data
