---
apiVersion: v1
kind: Service
metadata:
  name: snmp-default
  namespace: monitor
spec:
  selector:
    name: snmp-default
  ports:
  - port: 9116
    targetPort: 9116
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-default
  namespace: monitor
spec:
  selector:
    matchLabels:
      name: snmp-default
  replicas: 1
  template:
    metadata:
      labels:
        name: snmp-default
    spec:
      containers:
      - name: snmp-default
        image: prom/snmp-exporter
        ports:
        - containerPort: 9116
          protocol: TCP
