global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [localhost:9090]

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: [nodeexporter:9100]

  - job_name: grafana
    scrape_interval: 5s
    static_configs:
      - targets: [grafana:3000]

  - job_name: gpuexporter
    scrape_interval: 5s
    static_configs:
      - targets: [gpuexporter:9101]

  - job_name: apcupsd
    scrape_interval: 5s
    static_configs:
      - targets: [apc:9162]

  - job_name: snmp_nas
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /snmp
    params:
      module: [synology]
      target: [192.168.1.4]
    static_configs:
      - targets: [snmpexporter:9116]

  - job_name: snmp_router
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /snmp
    params:
      module: [udc]
      target: [192.168.1.1]
    static_configs:
      - targets: [snmpexporterrouter:9116]

  - job_name: snmp_switch
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /snmp
    params:
      module: [ddwrt]
      target: [192.168.34.2]
    static_configs:
      - targets: [snmpexporter:9116]

  - job_name: traefik
    scrape_interval: 5s
    static_configs:
      - targets: [traefik:8080]

  - job_name: blackbox
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
        - https://google.com
        - https://www.ntu.edu.tw
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: snmp_hp
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /snmp
    params:
      module: [hp]
      target: [192.168.1.5]
    static_configs:
      - targets: [snmpexporterhp:9116]
