{
 "title": "Toolmen DashBoard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server_job", "query": "up{job='node-exporter'}" },
   {
    "name": "gpu_job",
    "query": "nvidia_utilization_gpu{job='gpuexporter'}"
   },
   {
    "name": "gpus",
    "query": "nvidia_utilization_gpu{job='$gpu_job'}"
   },
   {
    "name": "ups_job",
    "query": "apcupsd_battery_time_left_seconds{job='apcupsd'}"
   },
   { "name": "nas_job", "query": "hrStorageUsed" },
   { "name": "router_job", "query": "ipNetToMediaPhysAddress" },
   { "name": "switch_job", "query": "${VAR_SWITCH_JOB}" },
   { "name": "traefik_job", "query": "traefik_config_reloads_total" },
   {
    "name": "blackbox_job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "blackbox_target",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job='$server_job'}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{job='$server_job',mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total{job='$server_job'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Ram Uasgae",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job='$server_job'} * 100) / node_memory_MemTotal_bytes{job='$server_job'})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{job='$server_job'}) / 86400"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job='$server_job',mode!='idle'}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='$server_job'}- node_memory_MemFree_bytes{job='node-exporter'} - node_memory_Buffers_bytes{job='node-exporter'} - node_memory_Cached_bytes{job='node-exporter'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job='$server_job'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job='$server_job'}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node_load1{job='$server_job'}", "legendFormat": "node_load1" },
    { "expr": "node_load5{job='$server_job'}", "legendFormat": "node_load5" },
    { "expr": "node_load15{job='$server_job'}", "legendFormat": "node_load15" }
   ]
  },
  {
   "title": "Temparature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job='$server_job'}",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='$server_job',device!~'^(md\\\\d+$|dm-)'}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job='$server_job',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job='$server_job'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job='$server_job',device='bond0'}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job='$server_job',device='bond0'}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "GPU usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_utilization_gpu{job='$gpu_job'}) / count(nvidia_utilization_gpu{job='$gpu_job'})"
    }
   ]
  },
  {
   "title": "GPU memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_memory_used{job='$gpu_job'}) / sum(nvidia_memory_total{job='$gpu_job'}) * 100"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization_gpu{job='$gpu_job'}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nvidia_memory_used{job='$gpu_job'} * 1000000",
     "legendFormat": "Used {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temparature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_temperature_gpu{job='$gpu_job'}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "APC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery Time Left",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "apcupsd_battery_time_left_seconds{job='$ups_job'}",
       "legendFormat": "{{model}}"
      }
     ]
    },
    {
     "title": "AC Voltage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "expr": "apcupsd_line_nominal_volts{job='$ups_job'}",
       "legendFormat": "nominal"
      },
      {
       "expr": "apcupsd_line_volts{job='$ups_job'}",
       "legendFormat": "actual"
      }
     ]
    },
    {
     "title": "Battery Charge Percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "apcupsd_battery_charge_percent{job='$ups_job'}",
       "legendFormat": "{{model}}"
      }
     ]
    },
    {
     "title": "UPS Load Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "apcupsd_ups_load_percent{job='$ups_job'}",
       "legendFormat": "{{model}}"
      }
     ]
    },
    {
     "title": "APC Watts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "apcupsd_apcupsd_nominal_power_watts{job='$ups_job'} * (apcupsd_ups_load_percent{job='$ups_job'} / 100)",
       "legendFormat": "{{model}}"
      },
      {
       "expr": "apcupsd_apcupsd_nominal_power_watts{job='$ups_job'}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Battery Voltage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "expr": "apcupsd_battery_nominal_volts{job='$ups_job'}",
       "legendFormat": "nominal"
      },
      {
       "expr": "apcupsd_battery_volts{job='$ups_job'}",
       "legendFormat": "actual"
      }
     ]
    },
    {
     "title": "Current Time On Battery",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "apcupsd_battery_time_on_seconds{job='$ups_job'}"
      }
     ]
    },
    {
     "title": "Cumulative Time On Battery",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "apcupsd_battery_cumulative_time_on_seconds_total{job='$ups_job'}"
      }
     ]
    },
    {
     "title": "Last Discharged Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(time() - apcupsd_apcupsd_last_transfer_off_battery{job='$ups_job'}) / 86400"
      }
     ]
    }
   ]
  },
  {
   "title": "Nas $nas_job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "repeat": "nas_job",
   "collapsed": true,
   "panels": [
    {
     "title": "systemFanStatus",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 38 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "systemFanStatus{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "cpuFanStatus",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 38 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "cpuFanStatus{job='$nas_job'}" }
     ]
    },
    {
     "title": "powerStatus",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 38 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "powerStatus{job='$nas_job'}" }
     ]
    },
    {
     "title": "systemStatus",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 38 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "systemStatus{job='$nas_job'}" }
     ]
    },
    {
     "title": "Disk Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "targets": [
      { "expr": "diskStatus{job='$nas_job'}" }
     ]
    },
    {
     "title": "Trafick",
     "type": "graph",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{job='$nas_job'}[5m])",
       "legendFormat": "In {{ifName}}"
      },
      {
       "expr": "irate(ifHCOutOctets{job='$nas_job'}[5m])",
       "legendFormat": "Out {{ifName}}"
      }
     ]
    },
    {
     "title": "Temperture",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "diskTemperature{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 52 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "ssCpuUser{job='$nas_job'} + ssCpuSystem{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 52 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "1 - (memCached{job='$nas_job'} + memAvailReal{job='$nas_job'}) / memTotalReal{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 52 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "1 - memAvailSwap{job='$nas_job'} / memTotalSwap{job='$nas_job'}"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 52 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(storageIOLA{job='$nas_job'})"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 52 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hrStorageUsed{job='$nas_job'}) / sum(hrStorageSize{job='$nas_job'})"
      }
     ]
    },
    {
     "title": "temperature",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 52 },
     "format": "celsius",
     "valueName": "current",
     "targets": [
      { "expr": "temperature{job='$nas_job'}" }
     ]
    },
    {
     "title": "Disk Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "storageIOLA{job='$nas_job'}", "legendFormat": "{{storageIODevice}}" }
     ]
    },
    {
     "title": "Volume Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "spaceIOLA15{job='$nas_job'}", "legendFormat": "load15" },
      { "expr": "spaceIOLA5{job='$nas_job'}", "legendFormat": "load5" },
      { "expr": "spaceIOLA1{job='$nas_job'}", "legendFormat": "load1" }
     ]
    },
    {
     "title": "Read  Write Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(spaceIONReadX{job='$nas_job'}[5m])",
       "legendFormat": "Read {{storageIODevice}}"
      },
      {
       "expr": "irate(spaceIONWrittenX{job='$nas_job'}[5m])",
       "legendFormat": "Write {{storageIODevice}}"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "laLoadInt{job='$nas_job'}", "legendFormat": "{{laNames}}" }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      { "expr": "memTotalReal{job='$nas_job'}", "legendFormat": "Total" },
      { "expr": "memAvailReal{job='$nas_job'}", "legendFormat": "Available" },
      { "expr": "memCached{job='$nas_job'}", "legendFormat": "Cache" },
      { "expr": "memBuffer{job='$nas_job'}", "legendFormat": "Buffer" },
      { "expr": "memShared{job='$nas_job'}", "legendFormat": "Share" }
     ]
    },
    {
     "title": "RAID Status",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 73 },
     "targets": [
      { "expr": "raidStatus{job='$nas_job'}" }
     ]
    }
   ]
  },
  {
   "title": "Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "ssCpuUser{job='$router_job'} + ssCpuSystem{job='$router_job'}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 40 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "1 - (memTotalFree{job='$router_job'}) / memTotalReal{job='$router_job'}"
      }
     ]
    },
    {
     "title": "UpTime",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sysUpTime{job='$router_job'} / 86400 / 100"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "laLoadFloat{job='$router_job'}", "legendFormat": "{{laNames}}" }
     ]
    },
    {
     "title": "Trafick",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{job='$router_job'}[1m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifHCOutOctets{job='$router_job'}[1m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "memAvailReal{job='$router_job'}",
       "legendFormat": "memAvailReal"
      },
      { "expr": "memBuffer{job='$router_job'}", "legendFormat": "memBuffer" },
      { "expr": "memCached{job='$router_job'}", "legendFormat": "memCached" },
      {
       "expr": "memTotalFree{job='$router_job'}",
       "legendFormat": "memTotalFree"
      },
      {
       "expr": "memTotalReal{job='$router_job'}",
       "legendFormat": "memTotalReal"
      }
     ]
    },
    {
     "title": "Physical Address",
     "type": "table",
     "gridPos": { "h": 9, "w": 5, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "ifPhysAddress{job='$router_job'}"
      }
     ]
    },
    {
     "title": "Address",
     "type": "table",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 50 },
     "targets": [
      {
       "expr": "ipNetToMediaPhysAddress{job='$router_job'}"
      }
     ]
    },
    {
     "title": "Packages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInUcastPkts{job='$router_job'}[1m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{job='$router_job'}[1m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Switch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trafick",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInOctets{job='$switch_job', ifDescr!~\"LAG.*\"}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutOctets{job='$switch_job', ifDescr!~\"LAG.*\"}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "LAG - trafick",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInOctets{job='$switch_job', ifDescr=~\"LAG.*\"}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutOctets{job='$switch_job', ifDescr=~\"LAG.*\"}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "Packages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInUcastPkts{job='$switch_job', ifDescr!~\"LAG.*\"}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutUcastPkts{job='$switch_job', ifDescr!~\"LAG.*\"}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "LAG - Packages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInUcastPkts{job='$switch_job', ifDescr=~\"LAG.*\"}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutUcastPkts{job='$switch_job', ifDescr=~\"LAG.*\"}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "BroadCast",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInBroadcastPkts{job='$switch_job'}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutBroadcastPkts{job='$switch_job'}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "Multicast",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInMulticastPkts{job='$switch_job'}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutMulticastPkts{job='$switch_job'}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "Ucast",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInUcastPkts{job='$switch_job'}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutUcastPkts{job='$switch_job'}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "NUcast",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInNUcastPkts{job='$switch_job'}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutNUcastPkts{job='$switch_job'}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "Packet queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInQLen{job='$switch_job'}[5m])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutQLen{job='$switch_job'}[5m])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "Discards",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInDiscards{job='$switch_job'}[1d])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutDiscards{job='$switch_job'}[1d])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "UnknownProtos",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 69 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInUnknownProtos{job='$switch_job'}[1d])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutUnknownProtos{job='$switch_job'}[1d])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "LAG name",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "ifAlias{job='$switch_job', ifAlias=~\".+\"}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 75 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifInErrors{job='$switch_job'}[1d])",
       "legendFormat": "In {{ifDescr}}"
      },
      {
       "expr": "irate(ifOutErrors{job='$switch_job'}[1d])",
       "legendFormat": "Out {{ifDescr}}"
      }
     ]
    },
    {
     "title": "UpTime",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 76 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sysUpTime{job='$switch_job'}) / 86400 / 100"
      }
     ]
    },
    {
     "title": "Physical Address",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 76 },
     "targets": [
      {
       "expr": "ifPhysAddress{job='$switch_job'}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traefik",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=\"$traefik_job\"}"
      }
     ]
    },
    {
     "title": "Successful Status  Count (5min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{job='$traefik_job', code=\"200\"}[5m])) by (backend)",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Bad Status  Count (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{job='$traefik_job', code!=\"200\",code!=\"302\"}[5m])) by (backend)",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Average response time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_backend_request_duration_seconds_sum{job='$traefik_job'}) / sum(traefik_backend_requests_total{job='$traefik_job'}) * 1000",
       "legendFormat": "Average response time"
      }
     ]
    },
    {
     "title": "Requests in last 5 minutes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{job='$traefik_job'}[5m])) by (backend)",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Bad Status with backend and code (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{job='$traefik_job', code!=\"200\"}[5m])) by (backend, code)",
       "legendFormat": "{{backend}} {{code}}"
      }
     ]
    },
    {
     "title": "Global latency  over 5 min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code='200', method='GET', job='$traefik_job'}[5m])) by (le)"
      }
     ]
    },
    {
     "title": "Apdex score (over 5 min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_request_duration_seconds_bucket{job='$traefik_job', le=\"0.1\", code=\"200\"}[5m])) / sum(rate(traefik_backend_request_duration_seconds_count{job='$traefik_job', code=\"200\"}[5m]))",
       "legendFormat": "Code 200"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections{job='$traefik_job'})",
       "legendFormat": "frontend"
      },
      {
       "expr": "sum(traefik_backend_open_connections{job='$traefik_job'}) by (backend)",
       "legendFormat": "backend {{ backend }}"
      }
     ]
    },
    {
     "title": "Total requests by backend",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "none", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total{job='$traefik_job'}) by (backend)",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Total requests by code",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total{job='$traefik_job'}) by (code) ",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Total requests by backend",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total{job='$traefik_job'}) by (backend) ",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Total requests by protocol",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total{job='$traefik_job'}) by (protocol) ",
       "legendFormat": "{{ protocol }}"
      }
     ]
    },
    {
     "title": "Total requests by method",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 96 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total{job='$traefik_job'}) by (method) ",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Total Bad Status with backend and code",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 96 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total{job='$traefik_job', code!=\"200\"}) by (backend, code)",
       "legendFormat": "{{backend}} {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_dns_lookup_time_seconds{job='$blackbox_job'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "All time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{job='$blackbox_job'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Live",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(probe_success{job='$blackbox_job'}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Phase $blackbox_target",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "repeat": "blackbox_target",
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_http_duration_seconds{job='$blackbox_job', instance=~'$blackbox_target'}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Phase $blackbox_target",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_http_duration_seconds{job='$blackbox_job', instance=~'$blackbox_target'}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Phase $blackbox_target",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_http_duration_seconds{job='$blackbox_job', instance=~'$blackbox_target'}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "https time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{job='$blackbox_job'}",
       "legendFormat": "{{instance}} - {{phase}}"
      }
     ]
    }
   ]
  }
 ]
}